//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDetailsTable
    {
        public int Id { get; set; }
        public decimal Science { get; set; }
        public decimal Maths { get; set; }
        public decimal EVS { get; set; }
        public decimal History { get; set; }
        public decimal English { get; set; }
        public decimal Hindi { get; set; }
        public decimal Percentage { get; set; }
        public string Result { get; set; }
        public string Remark { get; set; }
    }
}
